### ISSUE TITLE
Missing issue hook in the Typescript definition file

### ISSUE THREAD

**Issue by ghost** [excaliburhan/node-gitlab-webhook#4]
In your Typescript definition file your are exposing the available hooks right here:

https://github.com/excaliburhan/node-gitlab-webhook/blob/84f5777229cef953b7747675e56c644d4bc19e6d/index.d.ts#L381-L390

Unfortunately though you are missing out on one:

    on(type: 'issue', callback: (event: EventData<IssueEvent>) => void): void;

Currently I am not able to create a pull request, so I'd appreciate it if you can do this yourself.

**Comment by excaliburhan** [comment]
I have fixed this and pushed version 1.0.6, thanks.
