### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by MarcinHoppe** [excaliburhan/node-gitlab-webhook#6]
I'm a member of the Node.js Foundation Security Working Group and we received a report of a vulnerability in this module.

We tried inviting the author by e-mail but received no response so I'm opening this issue and inviting anyone with commit and npm publish rights to collaborate with us on a fix.

**Comment by excaliburhan** [comment]
Hi Marcin, I cant see the H1 report in my inbox, can you resend it? my email is edwardhjp@gmail.com

**Comment by excaliburhan** [comment]
> I'm a member of the Node.js Foundation Security Working Group and we received a report of a vulnerability in this module.
> 
> We tried inviting the author by e-mail but received no response so I'm opening this issue and inviting anyone with commit and npm publish rights to collaborate with us on a fix.

Thanks Marcin, I checked my code and find out you may need to contact this repo:  https://github.com/rolfn/node-gitlab-hook. I also replied in H1.

**Comment by MarcinHoppe** [comment]
Thanks for responding on HackerOne. I will close this issue.
